---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-licensing-scanner-operator-role
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ibm-licensing-scanner-operator
    app.kubernetes.io/instance: operator-cluster-role-binding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: ibm-licensing-scanner-operator
  name: ibm-licensing-scanner-operator-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-licensing-scanner-operator-role
subjects:
  - kind: ServiceAccount
    name: ibm-licensing-scanner-operator-service-account
    namespace: {{ .Values.namespace }}
