{{- if .Values.ibmLicensing.enableRoutes }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations: {}
  name: ibm-licensing-service-instance
  namespace: {{ .Values.ibmLicensing.namespace }}
spec:
  port:
    targetPort: api-port
  tls:
    insecureEdgeTerminationPolicy: None
    termination: reencrypt
  to:
    kind: Service
    name: ibm-licensing-service-instance
    weight: 100
{{- end }}
