apiVersion: v1
data:
  token: {{ randAlphaNum 24 | b64enc }}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: ibm-licensing-service-svc
    app.kubernetes.io/instance: ibm-licensing-service
    app.kubernetes.io/managed-by: operator
    app.kubernetes.io/name: ibm-licensing-service-instance
    release: ibm-licensing-service
  name: ibm-licensing-token
  namespace: {{ .Values.ibmLicensing.namespace }}
type: Opaque
---
apiVersion: v1
data:
  token-upload: {{ randAlphaNum 24 | b64enc }}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: ibm-licensing-service-svc
    app.kubernetes.io/instance: ibm-licensing-service
    app.kubernetes.io/managed-by: operator
    app.kubernetes.io/name: ibm-licensing-service-instance
    release: ibm-licensing-service
  name: ibm-licensing-upload-token
  namespace: {{ .Values.ibmLicensing.namespace }}
type: Opaque
