---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    productID: 105fa377cada4660a213f99e02c53782
    productMetric: FREE
    productName: IBM License Service Scanner
    {{- if ((.Values.operator).annotations) }}
      {{- toYaml .Values.operator.annotations | nindent 4 -}}
    {{ end }}
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/component: ibm-licensing-scanner-operator-deployment
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ibm-licensing-scanner
    app.kubernetes.io/version: 4.2.12
    control-plane: controller-manager
    {{- if ((.Values.operator).labels) }}
      {{- toYaml .Values.operator.labels | nindent 4 -}}
    {{ end }}
  name: ibm-licensing-scanner-operator
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: ibm-licensing-scanner-operator
        productID: 105fa377cada4660a213f99e02c53782
        productMetric: FREE
        productName: IBM License Service Scanner
        {{- if ((.Values.operator).annotations) }}
          {{- toYaml .Values.operator.annotations | nindent 4 -}}
        {{ end }}
      labels:
        app.kubernetes.io/component: ibm-licensing-scanner-operator-pod
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: ibm-licensing-scanner
        app.kubernetes.io/version: 4.2.12
        control-plane: controller-manager
        {{- if ((.Values.operator).labels) }}
          {{- toYaml .Values.operator.labels | nindent 4 -}}
        {{ end }}
    spec:
      containers:
        - args:
            - --leader-elect
          command:
            - ibm-license-service-scanner-operator
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: IBM_LICENSE_SERVICE_SCANNER_OPERAND_IMAGE
              value: icr.io/cpopen/cpfs/ibm-licensing-scanner:4.2.12
          image: {{ .Values.imagePullPrefix }}/cpopen/ibm-license-service-scanner-operator:4.2.12
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: ibm-licensing-scanner-operator
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      serviceAccountName: ibm-licensing-scanner-operator-service-account
      terminationGracePeriodSeconds: 10
      {{ if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- end -}}
