---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ibm-licensing-scanner-operator
    app.kubernetes.io/instance: leader-election-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: role
    app.kubernetes.io/part-of: ibm-licensing-scanner-operator
    component-id: {{ .Chart.Name }}
  name: ibm-licensing-scanner-leader-election-role
  namespace: {{ .Values.ibmLicenseServiceScanner.namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ibm-licensing-scanner-operand-role
  namespace: {{ .Values.ibmLicenseServiceScanner.namespace }}
  labels:
    component-id: {{ .Chart.Name }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - update
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ibm-licensing-scanner-operator-role
  namespace: {{ .Values.ibmLicenseServiceScanner.namespace }}
  labels:
    component-id: {{ .Chart.Name }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.ibm.com
    resources:
      - ibmlicenseservicescanners
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - operator.ibm.com
    resources:
      - ibmlicenseservicescanners/finalizers
    verbs:
      - update
  - apiGroups:
      - operator.ibm.com
    resources:
      - ibmlicenseservicescanners/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - operator.ibm.com
    resources:
      - operandrequests
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ibm-licensing-scanner-operator
    app.kubernetes.io/instance: leader-election-role-binding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: ibm-licensing-scanner-operator
    component-id: {{ .Chart.Name }}
  name: ibm-licensing-scanner-leader-election-role-binding
  namespace: {{ .Values.ibmLicenseServiceScanner.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-licensing-scanner-leader-election-role
subjects:
  - kind: ServiceAccount
    name: ibm-licensing-scanner-operator-service-account
    namespace: {{ .Values.ibmLicenseServiceScanner.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ibm-licensing-scanner-operator
    app.kubernetes.io/instance: operand-role-binding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: ibm-licensing-scanner-operator
    component-id: {{ .Chart.Name }}
  name: ibm-licensing-scanner-operand-role-binding
  namespace: {{ .Values.ibmLicenseServiceScanner.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-licensing-scanner-operand-role
subjects:
  - kind: ServiceAccount
    name: ibm-licensing-scanner-operand-service-account
    namespace: {{ .Values.ibmLicenseServiceScanner.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ibm-licensing-scanner-operator
    app.kubernetes.io/instance: operator-role-binding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: ibm-licensing-scanner-operator
    component-id: {{ .Chart.Name }}
  name: ibm-licensing-scanner-operator-role-binding
  namespace: {{ .Values.ibmLicenseServiceScanner.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-licensing-scanner-operator-role
subjects:
  - kind: ServiceAccount
    name: ibm-licensing-scanner-operator-service-account
    namespace: {{ .Values.ibmLicenseServiceScanner.namespace }}
