---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ibm-licensing-scanner-operator
    app.kubernetes.io/instance: operand-service-account
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: ibm-licensing-scanner-operator
    component-id: {{ .Chart.Name }}
  name: ibm-licensing-scanner-operand-service-account
  namespace: {{ .Values.ibmLicenseServiceScanner.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ibm-licensing-scanner-operator
    app.kubernetes.io/instance: operator-service-account
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: ibm-licensing-scanner-operator
    component-id: {{ .Chart.Name }}
  name: ibm-licensing-scanner-operator-service-account
  namespace: {{ .Values.ibmLicenseServiceScanner.namespace }}
