apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-licensing-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-licensing-operator
  template:
    metadata:
      annotations:
        productID: 068a62892a1e4db39641342e592daa25
        productMetric: FREE
        productName: IBM Cloud Platform Common Services
      labels:
        app.kubernetes.io/instance: ibm-licensing-operator
        app.kubernetes.io/managed-by: ibm-licensing-operator
        app.kubernetes.io/name: ibm-licensing
        name: ibm-licensing-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
      containers:
        - command:
            - ibm-licensing-operator
          env:
            - name: IBM_LICENSING_IMAGE
              value: icr.io/cpopen/cpfs/ibm-licensing:1.20.12
            - name: IBM_LICENSE_SERVICE_REPORTER_UI_IMAGE
              value: icr.io/cpopen/cpfs/ibm-license-service-reporter-ui:1.20.12
            - name: IBM_POSTGRESQL_IMAGE
              value: icr.io/cpopen/cpfs/ibm-postgresql:1.20.12
            - name: IBM_LICENSE_SERVICE_REPORTER_IMAGE
              value: icr.io/cpopen/cpfs/ibm-license-service-reporter:1.20.12
            - name: IBM_LICENSING_USAGE_IMAGE
              value: icr.io/cpopen/cpfs/ibm-licensing-usage:1.20.12
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.targetNamespaces']
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: ibm-licensing-operator
            - name: SA_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          image: icr.io/cpopen/ibm-licensing-operator:1.20.12
          imagePullPolicy: IfNotPresent
          name: ibm-licensing-operator
          resources:
            limits:
              cpu: 20m
              memory: 150Mi
            requests:
              cpu: 10m
              memory: 50Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
      serviceAccountName: ibm-licensing-operator
