apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-licensing-operator
  annotations:
    productID: 068a62892a1e4db39641342e592daa25
    productMetric: FREE
    productName: IBM Cloud Platform Common Services
  labels:
    app.kubernetes.io/instance: ibm-licensing-operator
    app.kubernetes.io/managed-by: ibm-licensing-operator
    app.kubernetes.io/name: ibm-licensing
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-licensing-operator
  template:
    metadata:
      annotations:
        productID: 068a62892a1e4db39641342e592daa25
        productMetric: FREE
        productName: IBM Cloud Platform Common Services
      labels:
        app.kubernetes.io/instance: ibm-licensing-operator
        app.kubernetes.io/managed-by: ibm-licensing-operator
        app.kubernetes.io/name: ibm-licensing
        name: ibm-licensing-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
      containers:
        - command:
            - ibm-licensing-operator
          env:
            - name: IBM_LICENSING_IMAGE
              value: icr.io/cpopen/cpfs/ibm-licensing:4.2.12
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.targetNamespaces']
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: ibm-licensing-operator
            - name: SA_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: CRD_RECONCILE_INTERVAL
              value: "300" 
          image: icr.io/cpopen/ibm-licensing-operator:4.2.12
          imagePullPolicy: IfNotPresent
          name: ibm-licensing-operator
          resources:
            limits:
              cpu: 20m
              memory: 150Mi
              ephemeral-storage: 500Mi
            requests:
              cpu: 10m
              memory: 50Mi
              ephemeral-storage: 250Mi
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
      serviceAccountName: ibm-licensing-operator
