{{- if .Values.renderParentApplicationOnly -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-licensing-components
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.spec.project }}
  destination:
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: deploy/argo/applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end -}}