apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-cd-manage-deployments
  namespace: ibm-ls-reporter
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-cd-manage-serviceaccounts
  namespace: ibm-ls-reporter
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-cd-manage-reporters
  namespace: ibm-ls-reporter
rules:
  - apiGroups:
      - operator.ibm.com
    resources:
      - ibmlicenseservicereporters
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-cd-manage-deployments-binding
  namespace: ibm-ls-reporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-cd-manage-deployments
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-cd-manage-serviceaccounts-binding
  namespace: ibm-ls-reporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-cd-manage-serviceaccounts
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-cd-manage-reporters-binding
  namespace: ibm-ls-reporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-cd-manage-reporters
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
