kind: IBMLicensing
apiVersion: operator.ibm.com/v1alpha1
metadata:
  name: instance
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
    argocd.argoproj.io/hook: PostSync
spec:
  {{- toYaml .Values.spec | nindent 2 }}