global:
  imagePullPrefix: icr.io
  imagePullSecret: ibm-entitlement-key
  licenseAccept: true

ibmLicensing:
  namespace: ibm-licensing
  watchNamespace: ibm-licensing
  # Comma-separated list of namespaces to exclude from license collection.
  excludeNamespace: ""
  imageRegistryNamespaceOperator: cpopen
  imageRegistryNamespaceOperand: cpopen/cpfs
  createRBAC: true
  createRBACInWatchedNamespaces: true
  podAnnotations: {}
  podLabels: {}
  affinity: {}
  nodeSelector: {}
  serviceAccount:
    name: ""
  spec:
    version: 4.2.25
    datasource: datacollector
    httpsEnable: true
    enableInstanaMetricCollection: false
    features:
      nssEnabled: false
      nodeCpuCappingEnabled: true
      kubeRBACAuthEnabled: true
      operandRequestsEnabled: true
      customResourcesEnabled: true

