namespace: ibm-licensing
watchNamespace: ibm-licensing

spec:
  version: 4.2.16
  apiSecretToken: ibm-licensing-token
  datasource: datacollector
  httpsEnable: true
  license:
    accept: true

global:
  imagePullPrefix: icr.io
  imagePullSecret: ibm-entitlement-key
cpfs:
  imageRegistryNamespaceOperator: cpopen
  imageRegistryNamespaceOperand: cpopen/cpfs