apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations: {}
  name: ibm-licensing-service-instance
  namespace: ibm-licensing
spec:
  port:
    targetPort: api-port
  tls:
    certificate: |-
      -----BEGIN CERTIFICATE-----
      MIIDoTCCAomgAwIBAgIDBT0qMA0GCSqGSIb3DQEBCwUAMGAxDDAKBgNVBAoTA0lC
      TTFQME4GA1UEAxNHaWJtLWxpY2Vuc2luZy1zZXJ2aWNlLWluc3RhbmNlLWlibS1s
      aWNlbnNpbmcuYXBwcy5hcHIxMy5jcC5meXJlLmlibS5jb20wHhcNMjYwNTI2MTQy
      ODU5WhcNMjcwNTI2MTQyODU5WjBgMQwwCgYDVQQKEwNJQk0xUDBOBgNVBAMTR2li
      bS1saWNlbnNpbmctc2VydmljZS1pbnN0YW5jZS1pYm0tbGljZW5zaW5nLmFwcHMu
      YXByMTMuY3AuZnlyZS5pYm0uY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
      CgKCAQEA3GgX2+Bw7dhgfVpCV/W549NmD3Mdrpidcw9CkhcrPqoySh0sJ8a1WQMg
      uCXS1OqEIBJvDuOM4SBNAi90sFFEPTgUuQ4eZHymZnqmfb6O3J4voucn8lvvydEF
      4juIUvGjkXZRnNvWE0K4QWrF5vyqZtw4BgDFPbSlYd42/juv+u1UcFUk9zEkDQ+O
      vuMuAV5FDcIjD7kozAY0ctW9HyVj0IZ8JPjzx7oFNlcPXBcCzBLmMD9FhwETpH1/
      Rmy2NFAzHBUknu6sFADw7L4vUqkEzoYLhPYUav8FT4C6/spp5Uuw2DtrX98G+wem
      1qG5ILlU18BdaeSEo6+p06rIN8zcbQIDAQABo2QwYjAMBgNVHRMBAf8EAjAAMFIG
      A1UdEQRLMEmCR2libS1saWNlbnNpbmctc2VydmljZS1pbnN0YW5jZS1pYm0tbGlj
      ZW5zaW5nLmFwcHMuYXByMTMuY3AuZnlyZS5pYm0uY29tMA0GCSqGSIb3DQEBCwUA
      A4IBAQCKke6N4+5bOMgiMUcATxv9bLsj4X+9vm2ZokRCHY6QmZA8azG20ZJ5opXM
      HkdOBua94SqJQ8X1e9Kn6UipzHZwTNOwEGT9S9CNCOYzKXsx0CrUYVs2oM6FtOPO
      vKdFPd/Zl3GDQwCtBvQFm6br219updVFeGyLJN1qR9oKF9LVlZyGaW3CuAYHJB9+
      sXX9NPgX/Hf1Ezm/B+kJHKWwDuK0jjE7lF3DFJYBZ3pldFVKqtD+HSs9PTJ9aQZS
      aYdu/2m3iP7k8mXYFedvDnmgp9WGsPItJl25zYdUKV0/BS9N2+qBKXFMLg20Y1d/
      5gG1Jxty2TX2EDjCdJeZ7mg67es+
      -----END CERTIFICATE-----
    destinationCACertificate: |-
      -----BEGIN CERTIFICATE-----
      MIIDUTCCAjmgAwIBAgIIKF4lWgShbhowDQYJKoZIhvcNAQELBQAwNjE0MDIGA1UE
      Awwrb3BlbnNoaWZ0LXNlcnZpY2Utc2VydmluZy1zaWduZXJAMTc3NjA3MTg3MDAe
      Fw0yNjA0MTMwOTE3NDlaFw0yODA2MTEwOTE3NTBaMDYxNDAyBgNVBAMMK29wZW5z
      aGlmdC1zZXJ2aWNlLXNlcnZpbmctc2lnbmVyQDE3NzYwNzE4NzAwggEiMA0GCSqG
      SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDIFjuy1mG3SG4RmPSfh6+9mYS+tFyrJIB3
      2Nwd+puDBbrmGT5kbhHHtg3UpiadT/r5vCKZwvPXY5l0OXdFVIyHXaXsIieuQce3
      Ld3e1Jro7dT+a4abMcIh7JgvWXb73WkYMRTELwNRQeIZGYH6JaJ5wxPyPnFVaCeb
      pc232Nys2ys2dkxtji39ndx0sOlQ+3H6K4daB0OsjLGfZYq/nWgVe200xK6Locfd
      ey4ab2k38nn2RaPnvI6VKxD02pLpxRTOFxuQf0Fd57WElyMS9sgwRigiPiGCz+3a
      3oWeNqyI7OBtpURdA1ntMoMaV3tMVxf2Kg/lwK6XGU0hpvuMZXaJAgMBAAGjYzBh
      MA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBR8HKzd
      qORWzT8rXrum/+bYg5Lj/jAfBgNVHSMEGDAWgBR8HKzdqORWzT8rXrum/+bYg5Lj
      /jANBgkqhkiG9w0BAQsFAAOCAQEAmZo7z4cMMDeejIrHgBkWX12B4NufqnbmbI3W
      a7EIIo5FcLBqEAzh9KsXKsIzqVTk8YDvf7nLspLrGQObFy0uRWpTnKnZDo08hDEk
      Ohwef1FRIkv6UxukopZAn4L+pRhJqZJA8XhGGDP8gpxFFSvi+gZZ5NAujq5/Zp2J
      S5S1WQBf4tInrlbhUvwUvAozJFJFoVODnpauO1yreKzkKe0K1Y+/GruIz/cWxN/Q
      1Anj68zx6z255ZLDL20e4yX0th0ucDHEYk0fYXJWt09aNnLlhGqNbdt1xgBjmgUD
      miOke3dUGKnusNkBl5e6wFd/eyUcKqWMv8enGHfwRB+HDXlB6Q==
      -----END CERTIFICATE-----
    insecureEdgeTerminationPolicy: None
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEA3GgX2+Bw7dhgfVpCV/W549NmD3Mdrpidcw9CkhcrPqoySh0s
      J8a1WQMguCXS1OqEIBJvDuOM4SBNAi90sFFEPTgUuQ4eZHymZnqmfb6O3J4voucn
      8lvvydEF4juIUvGjkXZRnNvWE0K4QWrF5vyqZtw4BgDFPbSlYd42/juv+u1UcFUk
      9zEkDQ+OvuMuAV5FDcIjD7kozAY0ctW9HyVj0IZ8JPjzx7oFNlcPXBcCzBLmMD9F
      hwETpH1/Rmy2NFAzHBUknu6sFADw7L4vUqkEzoYLhPYUav8FT4C6/spp5Uuw2Dtr
      X98G+wem1qG5ILlU18BdaeSEo6+p06rIN8zcbQIDAQABAoIBAC9I9bVqVU/xl+HM
      t2b/hL3n4IF4BOosO7svjuygo9px0RAtageujcFm9mILW0vqdCYdTk43a0XxFBRf
      8fzRsn4fxfJdoQ+V3m0l6woXE7cpCLc+OEe6iZsWiNicRQbmaF0QsTmhwC+ppLYE
      HikME9K1dB91kttGIiT483tfesWuNsxUh1tybnlhRNplwEPLj5yySRIzYy1nyYvl
      coqG5Thv19UEDgCqOjel/BNOfeieQpKimGrj3kifpkYJpQjqozOgNSaTaq6fWIP8
      ODlzgXiZHuYfxQRaitvBGnpWY6VDJGB+Hr5Ci7ju/flfsCq1X9fDB5okaqNaRVvU
      2WkmGYECgYEA/Ntz38C6O3E3LzrbFAgiDBtA7WaDiQvdaw2u8gVdbiHQIpKuyrzC
      +qOUwNEnyfx6v+t/+qCEXMprYxecOr2MQXs2yFDBpQI/svKNWBcIj/YvEODx25et
      fDhW9Cou2SW66UD6TsVqnzy3AvUrbL4YjFwzf0hXbk1NBC25A9W50AUCgYEA3yVj
      bK/8hJ2ZCuR8JSlOg4VxTOKXe8H/urBnbDPmsuiqi+HABK/sIxVEmyMam135rz8w
      2lmN9CqWGXUY9zrCREADtWZFxGRhfEJ/kSOrnoCauIYuHYL+hdgXrIx9TfgIC+mn
      O/yIwwKCCg45BQpUQ7EHTsdi53BL6TJlCRlTT0kCgYEA7m9l8d2D/1+AISpHwbj1
      miLs87ASYt3sWfGaQaArfRmncaKN7qFW3w/3ymawNXi+q1E/6i8JAZLi9psh+AYb
      RvgQLY5xO89GD9FG1YVKzq3frfPgPSjnL9bUsANDEALTIPbj0fm41BVlogVcgHs1
      HM4oxWKLB3kfIcyXxXT5dZ0CgYBYPpPj/nCRDTXhjdveYkhvUI0ux4j6Ywy7illL
      +/ZmmAYhzUO/Vsa+VQHNjANQn8hG2ml6X+H4RgMXzCv0USNUFDCjQu+iK8Q1fKKw
      BfgvdVI6WK3R8+Stj3hFP0WqWMTt2RfObB61Z79/NIKuEJikMFTgfY8KUWljrg8w
      mvhMKQKBgFoSsWN1ISCpGEyswp4pnV1iNUmMw2buu7arIgIPKV32pp0+0GUl6dge
      86Q7vGj2pTQvVIetz34YsdYsmqUk1x38hZ3g8hbDSITRPMYdP5hUvQi16+0g4hTF
      t6tTl7h8bprEFzj9ZvOnHhPAUy8X0m4JSvtd38TZcyiTyIdlwDro
      -----END RSA PRIVATE KEY-----
    termination: reencrypt
  to:
    kind: Service
    name: ibm-licensing-service-instance
    weight: 100
