apiVersion: v1
data:
  token: ZGRWTXNvZUFhQTJocHd1Q0hnTWI5c0sw
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: ibm-licensing-service-svc
    app.kubernetes.io/instance: ibm-licensing-service
    app.kubernetes.io/managed-by: operator
    app.kubernetes.io/name: ibm-licensing-service-instance
    release: ibm-licensing-service
  name: ibm-licensing-token
  namespace: ibm-licensing
type: Opaque
