---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ibm-licensing-scanner-auto-connect-role
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ibm-licensing-scanner-auto-connect-role-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-licensing-scanner-auto-connect-role
subjects:
  - kind: ServiceAccount
    name: ibm-licensing-operator
    namespace: {{ .Values.licenseServiceNamespace }}
---
