# permissions for end users to edit ibmlicenseservicereporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibmlicenseservicereporter-editor-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - ibmlicenseservicereporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - ibmlicenseservicereporters/status
  verbs:
  - get
