# permissions for end users to view ibmlicenseservicereporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibmlicenseservicereporter-viewer-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - ibmlicenseservicereporters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - ibmlicenseservicereporters/status
  verbs:
  - get
