# permissions for end users to edit ibmlicensings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibmlicensing-editor-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - ibmlicensings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - ibmlicensings/status
  verbs:
  - get
