# Adds namespace to all resources.
namespace: ibm-licensing

labels:
- pairs:
    app.kubernetes.io/instance: "ibm-licensing-operator"
    app.kubernetes.io/managed-by: "ibm-licensing-operator"
    app.kubernetes.io/name: "ibm-licensing"
  includeSelectors: false

resources:
- role.yaml
- role_binding.yaml
- role_operands.yaml
- service_account.yaml

