apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-license-service
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - get
      - list
  - apiGroups:
      - "metrics.k8s.io"
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - operator.ibm.com
    resources:
      - ibmlicensingmetadatas
      - ibmlicensingdefinitions
      - ibmlicensingquerysources
    verbs:
      - get
      - list
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-licensing-default-reader
rules:
  - nonResourceURLs:
      - "/products"
      - "/snapshot"
      - "/bundled_products"
      - "/health"
      - "/status"
      - "/services"
      - "/workloads"
    verbs:
      - "get"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ibm-license-service
  namespace: ibm-licensing
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - list
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-license-service-restricted
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - operator.ibm.com
    resources:
      - ibmlicensingmetadatas
      - ibmlicensingdefinitions
      - ibmlicensingquerysources
    verbs:
      - get
      - list
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ibm-license-service-restricted
  namespace: ibm-licensing
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - list
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
  - apiGroups:
    - "batch"
    resources:
    - jobs
    verbs:
     - list
     - get