kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-licensing-operator
  namespace: ibm-common-services
subjects:
  - kind: ServiceAccount
    name: ibm-licensing-operator
    namespace: ibm-common-services
roleRef:
  kind: ClusterRole
  name: ibm-licensing-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-licensing-operator
  namespace: ibm-common-services
subjects:
  - kind: ServiceAccount
    name: ibm-licensing-operator
    namespace: ibm-common-services
roleRef:
  kind: Role
  name: ibm-licensing-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-license-service
  namespace: ibm-common-services
subjects:
  - kind: ServiceAccount
    name: ibm-license-service
    namespace: ibm-common-services
roleRef:
  kind: Role
  name: ibm-license-service
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-license-service
  namespace: ibm-common-services
subjects:
  - kind: ServiceAccount
    name: ibm-license-service
    namespace: ibm-common-services
roleRef:
  kind: ClusterRole
  name: ibm-license-service
  apiGroup: rbac.authorization.k8s.io
