apiVersion: batch/v1
kind: Job
metadata:
  name: ibm-licensing-migration-job
  namespace: {{ .Values.global.operatorNamespace }}
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
spec:
  template:
    spec:
      containers:
      - name: ibm-licensing-migration-job
        image: {{ .Values.global.imagePullPrefix }}/{{ .Values.ibmLicensing.imageRegistryNamespaceOperand }}/cpfs-utils:4.6.7
        command:
          - bash
          - -c
          - |
            echo "Starting cleanup for OLM -> No OLM migration..."
            operatorNamespace={{ .Values.global.operatorNamespace }}

            subscription_name=$(oc get subscription.operators.coreos.com -n "$operatorNamespace" -o jsonpath="{.items[?(@.spec.name=='ibm-licensing-operator-app')].metadata.name}")
            if [[ -z $subscription_name ]]; then
              echo "Subscription $subscription_name not present in namespace $operatorNamespace, aborting."
            else
              # Delete subscription and CSV
              csv_name=$(oc get --ignore-not-found subscription.operators.coreos.com $subscription_name -n $operatorNamespace -o jsonpath='{.status.currentCSV}')
              echo "Deleting CSV $csv_name in namespace $operatorNamespace"
              oc delete --ignore-not-found csv $csv_name -n $operatorNamespace
              echo "Deleting Subscription $subscription_name in namespace $operatorNamespace"
              oc delete --ignore-not-found subscription.operators.coreos.com $subscription_name -n $operatorNamespace
            fi
      restartPolicy: Never
      serviceAccount: ibm-licensing-migration-job-sa
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}