apiVersion: batch/v1
kind: Job
metadata:
  name: ibm-licensing-migration-job
  namespace: {{ .Values.global.operatorNamespace }}
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
spec:
  template:
    spec:
      containers:
      - name: ibm-licensing-migration-job
        image: {{ .Values.global.imagePullPrefix }}/{{ .Values.ibmLicensing.cpfs.imageRegistryNamespaceOperand }}/cpfs-utils:4.6.7
        command:
          - bash
          - -c
          - |
            echo "Starting cleanup for OLM -> No OLM migration..."
            operatorNamespace={{ .Values.global.operatorNamespace }}

            subscription=$(oc get subscription.operators.coreos.com -n "$operatorNamespace" -o jsonpath="{.items[?(@.spec.name=='ibm-licensing-operator-app')].metadata.name}")
            if [[ -z $subscription ]]; then
              echo "Subscription not present in namespace $operatorNamespace, aborting."
            else
              # Delete Catalog Source
              catalogSourceName=$(oc get --ignore-not-found subscription.operators.coreos.com $subscription -n "$operatorNamespace" -o jsonpath='{.spec.source}')
              echo "Deleting Catalog Source $catalogSourceName in namespace $operatorNamespace..."
              oc delete catalogsource $catalogSourceName -n openshift-marketplace

              # Delete subscription and CSV
              CSV=$(oc get --ignore-not-found subscription.operators.coreos.com $subscription -n $operatorNamespace -o jsonpath='{.status.currentCSV}')
              echo "Deleting CSV and Subscription in namespace $operatorNamespace..."
              oc delete --ignore-not-found csv $CSV -n $operatorNamespace && oc delete --ignore-not-found subscription.operators.coreos.com $subscription -n $operatorNamespace
            fi
      restartPolicy: Never
      serviceAccount: ibm-licensing-migration-job-sa
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}