apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-licensing-migration-job-sa
  namespace: {{ .Values.global.operatorNamespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-licensing-migration-job-role-{{ .Values.global.operatorNamespace }}
  namespace: {{ .Values.global.operatorNamespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
rules: 
- apiGroups: 
  - operators.coreos.com
  resources:
  - subscriptions
  - clusterserviceversions
  verbs:
  - list
  - get
  - delete
  - watch
- apiGroups: 
  - "rbac.authorization.k8s.io"
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - list
  - get
  - delete
  - watch
- apiGroups: 
  - ""
  resources:
  - serviceaccounts
  - secrets
  verbs:
  - list
  - get
  - delete
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-licensing-migration-job-rb-{{ .Values.global.operatorNamespace }}
  namespace: {{ .Values.global.operatorNamespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
subjects:
  - kind: ServiceAccount
    name: ibm-licensing-migration-job-sa
    namespace: {{ .Values.global.operatorNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-licensing-migration-job-role-{{ .Values.global.operatorNamespace }}