---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    ibm-license-service: {{ .Chart.Name }}
  name: ibm-licensing-scanner-auto-connect-role
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    ibm-license-service: {{ .Chart.Name }}
  name: ibm-licensing-scanner-auto-connect-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-licensing-scanner-auto-connect-role
subjects:
  - kind: ServiceAccount
    name: ibm-licensing-operator
---
