---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ibm-licensing-operator
    app.kubernetes.io/managed-by: ibm-licensing-operator
    app.kubernetes.io/name: ibm-licensing
    ibm-license-service: {{ .Chart.Name }}
  name: ibm-license-service
  namespace: {{ .Values.ibmLicensing.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ibm-licensing-operator
    app.kubernetes.io/managed-by: ibm-licensing-operator
    app.kubernetes.io/name: ibm-licensing
    ibm-license-service: {{ .Chart.Name }}
  name: ibm-license-service-restricted
  namespace: {{ .Values.ibmLicensing.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ibm-licensing-operator
    app.kubernetes.io/managed-by: ibm-licensing-operator
    app.kubernetes.io/name: ibm-licensing
    ibm-license-service: {{ .Chart.Name }}
  name: ibm-licensing-default-reader
  namespace: {{ .Values.ibmLicensing.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ibm-licensing-operator
    app.kubernetes.io/managed-by: ibm-licensing-operator
    app.kubernetes.io/name: ibm-licensing
    ibm-license-service: {{ .Chart.Name }}
  name: ibm-licensing-operator
  namespace: {{ .Values.ibmLicensing.namespace }}
