apiVersion: operator.ibm.com/v1alpha1
kind: OperandBindInfo
metadata: 
  name: ibm-licensing-bindinfo
spec: 
  operand: ibm-licensing-operator
  registry: common-service
  description: Binding information that should be accessible to licensing adopters
  bindings:
    public-api-data:
      secret: ibm-licensing-token
      configmap: ibm-licensing-info
    public-api-token: 
      secret: ibm-licensing-token
    public-api-upload: 
      secret: ibm-licensing-upload-token
      configmap: ibm-licensing-upload-config
