apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-license-service
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: "https://github.com/IBM/ibm-licensing-operator"
    targetRevision: "ILS-59_add-argo"
    path: deploy/argo-cd/components/license-service
    helm:
      valuesObject:
        namespace: ibm-licensing
        watchNamespace: ibm-licensing,ibm-licensing-scanner
        spec:
          license:
            accept: true
