apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-license-service
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  sources:
    - repoURL: "https://github.com/IBM/ibm-licensing-operator"
      targetRevision: "test_argo_annotations"
      path: deploy/argo-cd/components/license-service/helm-cluster-scoped
      helm:
        valuesObject: {}
    - repoURL: "https://github.com/IBM/ibm-licensing-operator"
      targetRevision: "test_argo_annotations"
      path: deploy/argo-cd/components/license-service/helm
      helm:
        valuesObject: {}
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: ibmlicensingdefinitions.operator.ibm.com
      jsonPointers:
        - /metadata/labels/component-id
        - /metadata/labels/app.kubernetes.io~1instance
        - /metadata/labels/app.kubernetes.io~1name
        - /metadata/annotations/argocd.argoproj.io~1sync-wave
        - /metadata/labels/app.kubernetes.io~1managed-by
        - /metadata/annotations/meta.helm.sh~1release-namespace
        - /metadata/annotations/meta.helm.sh~1release-name
