apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-license-service
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: "https://github.com/IBM/ibm-licensing-operator"
    targetRevision: "master"
    path: deploy/argo-cd/components/license-service
