apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-license-service
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  sources:
    - repoURL: "https://github.com/IBM/ibm-licensing-operator"
      targetRevision: "ILS-402_helm-support"
      path: deploy/argo-cd/components/license-service/helm-cluster-scoped
    - repoURL: "https://github.com/IBM/ibm-licensing-operator"
      targetRevision: "ILS-402_helm-support"
      path: deploy/argo-cd/components/license-service/helm
