# Global settings
global:
  imagePullPrefix: icr.io
  imagePullSecret: ibm-entitlement-key

# IBM Licensing configuration
ibmLicensing:
  namespace: ibm-licensing
  imageRegistryNamespaceOperand: cpopen/cpfs
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 256Mi
      ephemeralStorage: 256Mi
  createRBAC: true
  datasource: datacollector
  httpsEnable: true
  enableInstanaMetricCollection: false
  httpsCertsSource: external
