namespace: ibm-licensing-scanner
licenseServiceNamespace: ibm-licensing

spec:
  license:
    accept: true
  license-service-upload-secret: ibm-licensing-scanner-upload-secret
  log-level: INFO
  registry-pull-secret: ibm-licensing-scanner-registry-pull-secret
  scan:
    namespaces:
      - ibm-licensing-scanner

global:
  imagePullPrefix: icr.io
  imagePullSecret: ibm-entitlement-key
cpfs:
  imageRegistryNamespaceOperator: cpopen
  imageRegistryNamespaceOperand: cpopen/cpfs
