global:
  operatorNamespace: ibm-licensing-scanner
  imagePullPrefix: icr.io
  imagePullSecret: ibm-entitlement-key
  licenseAccept: true
ibmLicenseServiceScanner:
  licenseServiceNamespace: ibm-licensing
  imageRegistryNamespaceOperator: cpopen
  imageRegistryNamespaceOperand: cpopen/cpfs
  spec:
    license-service-upload-secret: ibm-licensing-scanner-upload-secret
    log-level: INFO
    registry-pull-secret: ibm-licensing-scanner-registry-pull-secret
    scan:
      namespaces:
        - ibm-licensing-scanner
