apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: ibm-licensing-scanner-operator-deployment
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ibm-licensing-scanner
    app.kubernetes.io/version: 4.2.10
    control-plane: controller-manager
  name: ibm-licensing-scanner-operator
  namespace: ibm-licensing-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: ibm-licensing-scanner-operator
        productID: 105fa377cada4660a213f99e02c53782
        productMetric: FREE
        productName: IBM License Service Scanner
      labels:
        app.kubernetes.io/component: ibm-licensing-scanner-operator-pod
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: ibm-licensing-scanner
        app.kubernetes.io/version: 4.2.10
        control-plane: controller-manager
    spec:
      containers:
        - args:
            - --leader-elect
          command:
            - ibm-license-service-scanner-operator
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: IBM_LICENSE_SERVICE_SCANNER_OPERAND_IMAGE
              value: icr.io/cpopen/cpfs/ibm-licensing-scanner:4.2.10
          image: icr.io/cpopen/ibm-license-service-scanner-operator:4.2.10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: ibm-licensing-scanner-operator
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      serviceAccountName: ibm-licensing-scanner-operator-service-account
      terminationGracePeriodSeconds: 10
