namespace: &namespace ibm-licensing-scanner

# IBM License Service Scanner's (custom resource) spec
spec:
  license:
    accept: true
  license-service-upload-secret: ibm-licensing-scanner-upload-secret
  log-level: INFO
  registry-pull-secret: ibm-licensing-scanner-registry-pull-secret
  scan:
    namespaces:
      - *namespace
