apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ibmlicensings.operator.ibm.com
spec:
  group: operator.ibm.com
  names:
    kind: IBMLicensing
    listKind: IBMLicensingList
    plural: ibmlicensings
    singular: ibmlicensing
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: IBMLicensing is the Schema for the ibmlicensings API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: IBMLicensingSpec defines the desired state of IBMLicensing
          properties:
            apiSecretToken:
              type: string
            datasource:
              description: '?TODO: maybe change to enum in future:'
              type: string
            httpsCertsSource:
              description: '?TODO: maybe change to enum in future:'
              type: string
            httpsEnable:
              type: boolean
            imagePullSecrets:
              items:
                type: string
              type: array
            imageRegistry:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            imageTagPostfix:
              type: string
            instanceNamespace:
              type: string
            logLevel:
              description: '?TODO: maybe change to enum in future:'
              type: string
            securityContext:
              properties:
                runAsUser:
                  format: int64
                  type: integer
              required:
              - runAsUser
              type: object
          required:
          - apiSecretToken
          - datasource
          - httpsEnable
          - imageRegistry
          - imageTagPostfix
          - instanceNamespace
          type: object
        status:
          description: IBMLicensingStatus defines the observed state of IBMLicensing
          properties:
            licensingPods:
              description: LicensingPods are the names of the licensing pods
              items:
                type: string
              type: array
          required:
          - licensingPods
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
