# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/operator.ibm.com_ibmlicensings.yaml
- bases/operator.ibm.com_ibmlicensingmetadatas.yaml
- bases/operator.ibm.com_ibmlicensingdefinitions.yaml
- bases/operator.ibm.com_ibmlicensingquerysources.yaml
# +kubebuilder:scaffold:crdkustomizeresource

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml

commonLabels:
  app.kubernetes.io/instance: "ibm-licensing-operator"
  app.kubernetes.io/managed-by: "ibm-licensing-operator"
  app.kubernetes.io/name: "ibm-licensing"


