namespace: ibm-licensing
watchNamespace: ibm-licensing
spec:
  version: 4.2.12
  apiSecretToken: ibm-licensing-token
  datasource: datacollector
  httpsEnable: true
  license:
    accept: true

# Added for CI/CD
global:
  imagePullPrefix: icr.io
  imagePullSecret: ibm-entitlement-key
cpfs:
  imageRegistryNamespaceOperator: cpopen
  imageRegistryNamespaceOperand: cpopen/cpfs
