---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    productID: 068a62892a1e4db39641342e592daa25
    productMetric: FREE
    productName: IBM Cloud Platform Common Services
    {{- if ((.Values.operator).annotations) }}
      {{- toYaml .Values.operator.annotations | nindent 4 -}}
    {{ end }}
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: ibm-license-service-reporter-operator
    app.kubernetes.io/instance: ibm-license-service-reporter-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: deployment
    app.kubernetes.io/part-of: ibm-license-service-reporter-operator
    control-plane: ibm-license-service-reporter-operator
    {{- if ((.Values.operator).labels) }}
      {{- toYaml .Values.operator.labels | nindent 4 -}}
    {{ end }}
  name: ibm-license-service-reporter-operator
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: ibm-license-service-reporter-operator
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: ibm-license-service-reporter-operator
        productID: 068a62892a1e4db39641342e592daa25
        productMetric: FREE
        productName: IBM Cloud Platform Common Services
        {{- if ((.Values.operator).annotations) }}
          {{- toYaml .Values.operator.annotations | nindent 4 -}}
        {{ end }}
      labels:
        app.kubernetes.io/instance: ibm-license-service-reporter-operator
        app.kubernetes.io/managed-by: ibm-license-service-reporter-operator
        app.kubernetes.io/name: ibm-license-service-reporter
        control-plane: ibm-license-service-reporter-operator
        name: ibm-license-service-reporter-operator
        {{- if ((.Values.operator).labels) }}
          {{- toYaml .Values.operator.labels | nindent 4 -}}
        {{ end }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      containers:
        - args:
            - --leader-elect
          command:
            - ibm-license-service-reporter-operator
          env:
            - name: IBM_POSTGRESQL_IMAGE
              value: icr.io/cpopen/cpfs/ibm-postgresql:4.2.12
            - name: IBM_LICENSE_SERVICE_REPORTER_IMAGE
              value: icr.io/cpopen/cpfs/ibm-license-service-reporter:4.2.12
            - name: IBM_LICENSE_SERVICE_REPORTER_UI_IMAGE
              value: icr.io/cpopen/cpfs/ibm-license-service-reporter-ui:4.2.12
            - name: IBM_LICENSE_SERVICE_REPORTER_AUTH_IMAGE
              value: icr.io/cpopen/cpfs/ibm-license-service-reporter-oauth2-proxy:4.2.12
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['olm.targetNamespaces']
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: ibm-license-service-reporter-operator
            - name: SA_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          image: {{ .Values.imagePullPrefix }}/cpopen/ibm-license-service-reporter-operator:4.2.12
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: ibm-license-service-reporter-operator
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 10m
              ephemeral-storage: 500Mi
              memory: 64Mi
            requests:
              cpu: 10m
              ephemeral-storage: 256Mi
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      serviceAccountName: ibm-license-service-reporter-operator
      {{ if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- end -}}