---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ibm-license-service-reporter-operator
    app.kubernetes.io/instance: ibm-license-service-reporter
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: ibm-license-service-reporter-operator
    ibm-license-service-reporter: {{ .Chart.Name }}
  name: ibm-license-service-reporter
  namespace: {{ .Values.global.operatorNamespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ibm-license-service-reporter-operator
    app.kubernetes.io/instance: ibm-license-service-reporter-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: ibm-license-service-reporter-operator
    ibm-license-service-reporter: {{ .Chart.Name }}
  name: ibm-license-service-reporter-operator
  namespace: {{ .Values.global.operatorNamespace }}
