{{- if and .Values.ibmLicensing.createRBACInWatchedNamespaces .Values.ibmLicensing.createRBAC ((.Values.ibmLicensing.spec).features).nssEnabled }}
{{- $namespaces := splitList "," .Values.ibmLicensing.watchNamespace }}
{{- $operandServiceAccount := include "ibm-licensing.operandServiceAccount" . }}
{{- range $namespace := $namespaces }}
{{- $trimmedNamespace := trim $namespace }}
{{- if $trimmedNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: ibm-licensing-operator
    app.kubernetes.io/managed-by: ibm-licensing-operator
    app.kubernetes.io/name: ibm-licensing
    component-id: {{ $.Chart.Name }}
  name: ibm-license-service-watch
  namespace: {{ $trimmedNamespace }}
rules:
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
    - list
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - get
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: ibm-licensing-operator
    app.kubernetes.io/managed-by: ibm-licensing-operator
    app.kubernetes.io/name: ibm-licensing
    component-id: {{ $.Chart.Name }}
  name: ibm-license-service-watch
  namespace: {{ $trimmedNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-license-service-watch
subjects:
- kind: ServiceAccount
  name: {{ $operandServiceAccount }}
  namespace: {{ $.Values.ibmLicensing.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: ibm-licensing-operator
    app.kubernetes.io/managed-by: ibm-licensing-operator
    app.kubernetes.io/name: ibm-licensing
    component-id: {{ $.Chart.Name }}
  name: ibm-licensing-operator-watch
  namespace: {{ $trimmedNamespace }}
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - secrets
    - services
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - get
    - list
    - watch
{{- if (($.Values.ibmLicensing.spec).features).operandRequestsEnabled }}
- apiGroups:
    - ""
  resources:
    - configmaps
  verbs:
    - get
    - list
    - watch
    - create
    - update
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - create
    - update
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: ibm-licensing-operator
    app.kubernetes.io/managed-by: ibm-licensing-operator
    app.kubernetes.io/name: ibm-licensing
    component-id: {{ $.Chart.Name }}
  name: ibm-licensing-operator-watch
  namespace: {{ $trimmedNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-licensing-operator-watch
subjects:
- kind: ServiceAccount
  name: ibm-licensing-operator
  namespace: {{ $.Values.ibmLicensing.namespace }}
{{- end }}
{{- end }}
{{- end }}
