# Empty CR to not override existing CR, needed so that helm install --take-ownership adds correct labels/annotations on existing CR
apiVersion: operator.ibm.com/v1alpha1
kind: IBMLicensing
metadata:
  name: instance
  namespace: {{ .Values.ibmLicensing.namespace }}
spec: