apiVersion: batch/v1
kind: Job
metadata:
  name: ibm-licensing-migration-job
  namespace: {{ .Values.ibmLicensing.namespace }}
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
spec:
  template:
    spec:
      containers:
      - name: ibm-licensing-migration-job
        image: {{ .Values.global.imagePullPrefix }}/{{ .Values.ibmLicensing.imageRegistryNamespaceOperand }}/cpfs-utils:4.6.7
        command: # Removes Subscription, CSV and OperatorGroup
          - bash
          - -c
          - |
            echo "Starting cleanup for OLM -> No OLM migration..."

            operatorNamespace={{ .Values.ibmLicensing.namespace }}

            subscription_name=$(oc get --ignore-not-found subscription.operators.coreos.com -n "$operatorNamespace" -o jsonpath="{.items[?(@.spec.name=='ibm-licensing-operator-app')].metadata.name}")

            if [[ -z $subscription_name ]]; then
              echo "Subscription $subscription_name not present in namespace $operatorNamespace, aborting."
              exit 1
            fi

            # Get CSV and Operator Group names
            csv_name=$(oc get --ignore-not-found subscription.operators.coreos.com $subscription_name -n $operatorNamespace -o jsonpath='{.status.currentCSV}')
            operatorgroup_name=$(oc get --ignore-not-found csv "$csv_name" -n "$operatorNamespace" -o jsonpath='{.metadata.annotations.olm\.operatorGroup}')

            echo "Deleting CSV $csv_name in namespace $operatorNamespace"
            oc delete --ignore-not-found csv $csv_name -n $operatorNamespace

            echo "Deleting Subscription $subscription_name in namespace $operatorNamespace"
            oc delete --ignore-not-found subscription.operators.coreos.com $subscription_name -n $operatorNamespace

            echo "Deleting operatorGroup $operatorgroup_name in namespace $operatorNamespace"
            oc delete --ignore-not-found operatorgroup $operatorgroup_name -n $operatorNamespace

      restartPolicy: Never
      serviceAccount: ibm-licensing-migration-job-sa
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}