apiVersion: batch/v1
kind: Job
metadata:
  name: ibm-licensing-migration-job
  namespace: {{ .Values.ibmLicensing.namespace }}
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "3"
spec:
  template:
    spec:
      containers:
      - name: ibm-licensing-migration-job
        image: {{ .Values.global.imagePullPrefix }}/{{ .Values.ibmLicensing.imageRegistryNamespaceOperand }}/cpfs-utils:4.6.7
        command:
          - bash
          - -c
          - |
            echo "Starting cleanup for OLM -> No OLM migration..."

            namespace={{ .Values.ibmLicensing.namespace }}

            subscription_name=$(oc get --ignore-not-found subscription.operators.coreos.com -n "$namespace" -o jsonpath="{.items[?(@.spec.name=='ibm-licensing-operator-app')].metadata.name}")

            if [[ -z $subscription_name ]]; then
              echo "Subscription $subscription_name not present in namespace $namespace, aborting."
              exit 1
            fi

            # Get CSV and Operator Group names
            csv_name=$(oc get --ignore-not-found subscription.operators.coreos.com $subscription_name -n $namespace -o jsonpath='{.status.currentCSV}')
            operatorgroup_name=$(oc get --ignore-not-found csv "$csv_name" -n "$namespace" -o jsonpath='{.metadata.annotations.olm\.operatorGroup}')

            echo "Deleting CSV $csv_name in namespace $namespace"
            oc delete --ignore-not-found csv $csv_name -n $namespace

            echo "Deleting Subscription $subscription_name in namespace $namespace"
            oc delete --ignore-not-found subscription.operators.coreos.com $subscription_name -n $namespace

            echo "Deleting operatorGroup $operatorgroup_name in namespace $namespace"
            oc delete --ignore-not-found operatorgroup $operatorgroup_name -n $namespace

      restartPolicy: Never
      serviceAccount: ibm-licensing-migration-job-sa
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}