apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-licensing-migration-job-sa
  namespace: {{ .Values.ibmLicensing.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-licensing-migration-job-role
  namespace: {{ .Values.ibmLicensing.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
rules: 
- apiGroups: 
  - operators.coreos.com
  resources:
  - subscriptions
  - clusterserviceversions
  - operatorgroups
  verbs:
  - list
  - get
  - delete
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-licensing-migration-job-rb
  namespace: {{ .Values.ibmLicensing.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
subjects:
  - kind: ServiceAccount
    name: ibm-licensing-migration-job-sa
    namespace: {{ .Values.ibmLicensing.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-licensing-migration-job-role