#
# Copyright 2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: kind

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "0 0 * * *"    
  push:
      branches:
        - master
        - development
jobs:
  scorecard:
    name: Scorecrd tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        make build
        curl -Lo ./operator-sdk "https://github.com/operator-framework/operator-sdk/releases/download/v1.1.0/operator-sdk-v1.1.0-x86_64-linux-gnu"
        chmod +x ./operator-sdk
        curl -Lo ./kind "https://kind.sigs.k8s.io/dl/v0.9.0/kind-$(uname)-amd64"
        chmod +x ./kind
        ./kind create cluster --image kindest/node:v1.17.2
        ./kind get clusters
        kubectl config get-contexts
        kubectl config set-context kind-kind

    - name: Install OLM
      run: |
        kubectl apply -f https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.13.0/crds.yaml
        kubectl apply -f https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.13.0/olm.yaml
   
    - name: Deploy Operators YAML
      run: |
        kubectl create namespace ibm-common-services
        kubectl apply -f ./deploy/crds/operator.ibm.com_ibmlicenseservicereporters_crd.yaml
        kubectl apply -f ./deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
        kubectl apply -f ./deploy/service_account.yaml -n ibm-common-services
        kubectl apply -f ./deploy/role.yaml
        kubectl apply -f ./deploy/role_binding.yaml 
    - name: Run Scorecard tests
      run: |
        cp ./common/scripts/tests/.osdk-scorecard.yaml ./.osdk-scorecard.yaml
        export VERSION=1.3.0
        set -o pipefail
        ./operator-sdk scorecard namespace ibm-common-services --config ./.osdk-scorecard.yaml -b ./deploy/olm-catalog/ibm-licensing-operator/$VERSION/  --verbose 2>&1 | tee ./scorecard_logs.txt

    - name: Archive scorecard logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: scorecard results
        path: ./*.txt
    
     
  setup-build-publish-deploy:
    name: Operator tests on KinD
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Setup BATS
      uses: mig4/setup-bats@v1
      with:
        bats-version: 1.1.0

    - name: Checkout
      uses: actions/checkout@v2

    - name: Download binaries
      env:
        JSON_ARTIFACTORY: ${{ secrets.JSON_ARTIFACTORY }}
      run: |
        curl -Lo ./operator-sdk "https://github.com/operator-framework/operator-sdk/releases/download/v1.1.0/operator-sdk-v1.1.0-x86_64-linux-gnu"
        chmod +x ./operator-sdk
        wget https://github.com/kubernetes-sigs/kind/releases/download/v0.8.0/kind-linux-amd64
        mv ./kind-linux-amd64 ./kind
        chmod +x ./kind
        cp ./common/scripts/tests/kind_config.yaml ./
        echo "$JSON_ARTIFACTORY" > ./artifactory.yaml
        ./kind create cluster --image kindest/node:v1.17.2 --config ./kind_config.yaml --name tests
        kubectl config set-context kind-tests        
        kubectl get nodes

    - name: Test Operator - License Service
      run: |
        export PATH=`pwd`:$PATH
        export SUFIX=$RANDOM
        bats ./common/scripts/tests/tests.bats > ./test_logs.txt 2>&1
       
    - name: Archive logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: operator results
        path: ./*.txt


