#
# Copyright 2021 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: ocp

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "0 0 * * *"    
  push:
    branches:
      - master
      - development

# Environment variables available to all jobs and steps in this workflow
jobs:
  setup-build-publish-deploy:
    name: Operator tests on OCP
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Checkout
      uses: actions/checkout@v2

    - name: Download binaries
      env:
        ROKS_TOKEN: ${{ secrets.ROKS_TOKEN }}
        JSON_ARTIFACTORY: ${{ secrets.JSON_ARTIFACTORY }}
      run: |
        echo $RANDOM > ./random.txt
        export SUFIX=`cat ./random.txt`
        echo "$JSON_ARTIFACTORY" > ./artifactory.yaml
        export MUTEX_ON=true
        export MUTEX_OFF=false
        wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.6.0/openshift-client-linux-4.6.0.tar.gz
        tar -xvf ./openshift-client-linux-4.6.0.tar.gz
        ls -l
        echo "0"
        ./oc login --token="${{secrets.ROKS_TOKEN}}" 
        echo "a"
        ./oc get nodes
        ./common/scripts/tests/clear_ocp.sh

    - name: Test Unit Operator with CodeCoverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        export PATH=`pwd`:$PATH
        export USE_EXISTING_CLUSTER=true
        export SUFIX=`cat ./random.txt`
        export NAMESPACE=ibm-common-services$SUFIX
        export WATCH_NAMESPACE=ibm-common-services$SUFIX
        export OCP=true
        ./oc get nodes
        if [[ $GITHUB_BASE_REF == 'development' || $GITHUB_REF == 'refs/heads/development' ]]
        then
          make coverage-kind-development > ./test_coverage.txt 2>&1
        else
          make coverage-kind > ./test_coverage.txt 2>&1
        fi

    - name: Check all pods
      if: always()
      run: |
        export PATH=`pwd`:$PATH
        ./oc get nodes
        kubectl describe pods --all-namespaces  > ./pods.txt 2>&1

    - name: Clear
      if: always()
      run: |
        export MUTEX_ON=false
        export MUTEX_OFF=true
        export SUFIX=`cat ./random.txt`
        ./oc get nodes
        ./common/scripts/tests/clear_ocp.sh

    - name: Archive logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: operator results
        path: ./*.txt


