#
# Copyright 2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: ocp

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - development

# Environment variables available to all jobs and steps in this workflow
env:
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}

jobs:
  setup-build-publish-deploy:
    name: Operator tests on OCP
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Setup BATS
      uses: mig4/setup-bats@v1
      with:
        bats-version: 1.1.0

    # Download and Install IBM Cloud CLI
    - name: Install IBM Cloud CLI
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud --version
        ibmcloud config --check-version=false
        ibmcloud plugin install -f kubernetes-service
        ibmcloud plugin install -f container-registry

    # Authenticate with IBM Cloud CLI
    - name: Authenticate with IBM Cloud CLI
      run: |
        ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r eu-de -g SREREFARCH
        ibmcloud cr region-set eu-de
        ibmcloud cr login

    - name: Checkout
      uses: actions/checkout@v2

    - name: Download binaries
      env:
        JSON_ARTIFACTORY: ${{ secrets.JSON_ARTIFACTORY }}
      run: |
        echo $RANDOM > ./random.txt
        export SUFIX=`cat ./random.txt`
        echo "$JSON_ARTIFACTORY" > ./artifactory.yaml
        wget https://github.com/operator-framework/operator-sdk/releases/download/v0.17.0/operator-sdk-v0.17.0-x86_64-linux-gnu
        mv ./operator-sdk-v0.17.0-x86_64-linux-gnu ./operator-sdk
        chmod +x ./operator-sdk
        export MUTEX_ON=true
        export MUTEX_OFF=false
        ./common/scripts/tests/connect_ocp.sh
        ./common/scripts/tests/clear_ocp.sh


    - name: Test Operator
      run: |
        export PATH=`pwd`:$PATH
        export SUFIX=`cat ./random.txt`
        bats ./common/scripts/tests/tests.bats > ./test_logs.txt 2>&1


    - name: Clear
      if: always()
      run: |
        export MUTEX_ON=false
        export MUTEX_OFF=true
        export SUFIX=`cat ./random.txt`
        ./common/scripts/tests/clear_ocp.sh

    - name: Archive logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: operator results
        path: ./*.txt


